CREATE TABLE IF NOT EXISTS CANDIDATE (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name VARCHAR NOT NULL,
    voteCount INTEGER DEFAULT 0
);

CREATE TABLE IF NOT EXISTS USER (
    email VARCHAR NOT NULL UNIQUE PRIMARY KEY,
    password VARCHAR NOT NULL,
    name VARCHAR NOT NULL
);
